config/routes.rb
LehaziCom::Application.routes.draw do

  resources :ads

  resources :friend_links

if Rails.env.development?
  match "/images/uploads/*path" => "gridfs#serve"
end
  get "index/friend_links" => "friend_links#index" ,:as => "friend_links"

  get "blogs"  => "blog#index", :as => "blogs"

  root :to => "home#index"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "we" =>  "we#index", :as => "we"
  get "tieba" =>  "we#tieba", :as => "tieba"
  get "tianya" =>  "we#tianya", :as => "tianya"
  get "douban" =>  "we#douban", :as => "douban"

  resources :tags

  resources :users  do
    resources :entries do
      resources :comments
    end

    resources :roles
      member do
        put "enable"
    end

  end
  resources :games do
    collection do
      get 'admin'
    end
  end
  resources :articles  do
    collection do
      get 'admin'
      get 'tag/:tag_id' ,:action => "index"
    end
  end
  resources :funs do
    collection do
      get 'admin'
      get 'tag/:tag_id' ,:action => "index"
    end
   end
  resources :novels  do
    collection do
      get 'admin'
    end
  end
  resources :categories  do
    collection do
      get 'admin'
    end
    resources :articles#, :name_prefix => 'category_' ,:path_prefix => '/categories/:category_id'
    resources :funs
    resources :games
  end

  resource :topics do
    collection do
      get 'tag/:tag_id' ,:action => "index"
    end
  end
  resources :forums do
    resources :topics do
      collection do
        get "newtopic"
        get "last"
      end
       resources :posts
    end
  end

  resources :sessions
  resources :infos

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  belongs_to :category

  validates_presence_of :title
  validates_presence_of :synopsis
  validates_presence_of :body
  validates_presence_of :title
  validates_length_of :title, :maximum => 255
  validates_length_of :synopsis, :maximum => 1000
  validates_length_of :body, :maximum => 20000

  before_save :update_published_at

  def update_published_at
    self.published_at = Time.now if published == true
  end

end

app/controllers/articles_controller.rb
# encoding: utf-8
class ArticlesController < ApplicationController
  include TagsHelper

  before_filter :check_editor_role, :except => [:index, :show]

  def index
    @title = "娱乐信息"
    @keywords = '网文,小笑话,好笑,乐一下,了下,乐哈,gaoxiao,leha'
    @description = "娱乐新闻、搞笑网文、weibo笑话、微博趣事、围脖搞笑、八卦、明星"

    if params[:category_id]
       @articles = Article.where("category_id=#{params[:category_id].to_i} AND published=true").paginate(:page => params[:page],
                                                    :include => :user).order ( 'published_at DESC')
       @article_category = Category.find(params[:category_id])
    else
       if params[:tag_id]
         @tag_name = Tag.find(params[:tag_id]).name
          @title <<"_" <<  @tag_name
          @keywords = @tag_name
         @articles = Article.where( "taggings.tag_id = #{params[:tag_id].to_i} and taggings.taggable_type = 'article'").joins(" right join taggings on articles.id = taggable_id").paginate(:page => params[:page], :per_page => 10,
                                                    :include => :user,  :readonly => false).order ( 'articles.published_at DESC')
       else
      @articles = Article.where(:published => true).paginate(:page => params[:page],
                                                    :include => :user).order('published_at DESC')
       end

    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml {render :xml =>@articles.to_xml }
      format.rss {render :action => 'rss.rxml',:layout => false }
      format.atom {render :action => 'atom.rxml',:layout => false }
    end
  end

  def show
    if is_logged_in? && @current_user.has_roles?('Editor')
      @article =Article.find(params[:id])
    else
      @article = Article.find_by_id_and_published(params[:id], true)
    end

    @title = @article.title  + '_' + @article.category.name
    @keywords = tag_get("article", @article.id, 20)
    @description = @article.synopsis.truncate(255)

    respond_to do |format|
      format.html
      format.xml { render :xml => @article.to_xml }
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create(params[:article])
    @current_user.articles << @article
    respond_to do |format|
      format.html { redirect_to admin_articles_url }
      format.xml  { render :xml => @article.to_xml }
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update_attributes(params[:article])
    respond_to do |format|
      format.html {redirect_to admin_articles_url}
      format.xml  {render :xml => @article.to_xml }
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html {redirect_to admin_articles_url}
      format.xml  {render :nothing => true }
    end
  end

  def admin
     @articles = Article.paginate(:page => params[:page],
                                                    :include => :user).order('published_at DESC')
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    标题<br />
    <%= f.text_field :title, :size => 60 %>
  </div>
  <div class="field">
    简介<br />
    <%= f.text_area :synopsis, :rows => 4 , :cols => 60 %>
  </div>
   <div class="field">
    内容<br />
    <%= f.text_area :body, :row => 20, :cols => 60 %>
  </div>
  <div class="field">
    目录<br />
    <%= f.collection_select :category_id, category_id, Category.find(all), :id, :name %>
  </div>

  </div>
  <div class="field">
    发布? <%= f.check_box :published %>
  </div>
  <div class="actions">
    <%= f.submit  '提交' %>
    <%= link_to '取消'  ,articles_url %>
  </div>
<% end %>

app/views/articles/admin.html.erb
<h2>管理</h2>

<p><%=	 link_to '新建', new_article_path %></p>
<ul>
<% @articles.each  do |article| %>
    <li>
      <%=	 link_to article.title, article %>
      <%=   article.published ? '已发布' : '未发布' %>
      <%=	 link_to 'Edit', edit_article_path(article) %>
      <%=	 link_to 'Delete', article, method: :delete, :confirm => 'Are you sure?' %>
    </li>
<% end %>
</ul>
<%= will_paginate @articles ,:class => 'digg_pagination' %>
<style type="text/css">
  #menubar a.m_arti{background: #9999ff;    color:#FFF;}
#menubar a.m_funs,a.m_home,a.m_novel,a.m_game,a.m_baidu, a.m_tianya,a.m_le{}
</style>

app/views/articles/edit.html.erb
<h2>编辑</h2>

<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    标题<br />
    <%= f.text_field :title, :size => 60 %>
  </div>
  <div class="field">
    简介<br />
    <%= f.text_area :synopsis, :rows => 4 , :cols => 60 %>
  </div>
   <div class="field">
    内容<br />
    <%= f.text_area :body, :row => 20, :cols => 60 %>
  </div>
  <div class="field">
    目录<br />
    <%= f.collection_select :category_id, Category.find(:all), :id, :name, :include_blank => true %>
  </div>

  </div>
  <div class="field">
    发布? <%= f.check_box :published %>
  </div>
  <div class="field">
    <%= f.submit  '提交' %>
    <%= link_to '取消'  ,articles_url %>
  </div>
<% end %>
<style type="text/css">
  #menubar a.m_arti{background: #9999ff;    color:#FFF;}
#menubar a.m_funs,a.m_home,a.m_novel,a.m_game,a.m_baidu, a.m_tianya,a.m_le{}
</style>

app/views/articles/index.html.erb
<% content_for :head do %>
    <%= auto_discovery_link_tag	  %>
<% end %>
<div class="span-23">
  <hgroup>
    <label>当前位置： </label>
    <%=	 link_to '娱乐信息', funs_path %>  >
     <% if !@article_category.nil?  %>
        <%= link_to @article_category.name , category_funs_path(@article_category) %>  >
     <% end %>
    <%=	 @tag_name.blank? ? "列表" : @tag_name %>

  <span style="float: right;">
      <label>热门搜索：</label>

  </span>
  </hgroup>
  <hr>
</div>
<div class="span-23">

</div>
<div class="span-19">
    <table>
      <tbody>
<%	 @articles.each do |article| %>

      <tr>
        <td><% if article.category  %>
            <%= link_to '['+article.category.name+'] ', category_articles_path(article.category) %>
            <% end %></td>
        <td><%=link_to article.title, article %></td>
        <td><%= article.created_at.to_s(:short) %></td>
      </tr>

<% end %>
    </tbody>
</table>
<%= will_paginate @articles ,:class => 'digg_pagination' %>
</div>

<div class="span-4 last">
    <ul>
      <li><%= link_to '贴吧热贴' , tieba_path , :target => '_blank'%></li>
      <li><%= link_to '天涯热贴' , tianya_path , :target => '_blank' %></li>
      <li><%= link_to '豆瓣直播' , douban_path , :target => '_blank' %></li>
    </ul>
    <div class="prepend-top">
      <%= render :partial =>'layouts/tagscloud' ,:locals => {:model => "article"}%>
    </div>
</div>
<style type="text/css">
  #menubar a.m_arti{background: #9999ff;    color:#FFF;}
#menubar a.m_funs,a.m_home,a.m_novel,a.m_game,a.m_baidu, a.m_tianya,a.m_le{}
</style>

app/views/articles/new.html.erb
<h2>新建</h2>

<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    标题<br />
    <%= f.text_field :title, :size => 60 %>
  </div>
  <div class="field">
    简介<br />
    <%= f.text_area :synopsis, :rows => 4 , :cols => 60 %>
  </div>
   <div class="field">
    内容<br />
    <%= f.text_area :body, :row => 20, :cols => 60 %>
  </div>
  <div class="field">
    分类<br />
    <%= f.collection_select :category_id, Category.find(:all), :id, :name %>
  </div>

  </div>
  <div class="field">
    发布? <%= f.check_box :published %>
  </div>
  <div class="field">
    <%= f.submit  '提交' %>
    <%= link_to '取消'  ,articles_url %>
  </div>
<% end %>
<style type="text/css">
  #menubar a.m_arti{background: #9999ff;    color:#FFF;}
#menubar a.m_funs,a.m_home,a.m_novel,a.m_game,a.m_baidu, a.m_tianya,a.m_le{}
</style>

app/views/articles/show.html.erb
<div class="article">
  <div class="a_title">
<h2><%= @article.title  %></h2>
  </div>
  <div class="a_attr">
      <% if @article.category  %>
      <p class="category">
        分类：<%= link_to @article.category.name, category_articles_path(@article.category) %>
      </p>
      <% end %>
    <%= @article.created_at.to_s(:short) %>
  </div>
  <div class="a_content">
        <%=	 raw(@article.body) %>
  </div>
  <div class="a_author">

  </div>
  <p><%= link_to '返回' , articles_url %></p>
</div>
<style type="text/css">
  #menubar a.m_arti{background: #9999ff;    color:#FFF;}
#menubar a.m_funs,a.m_home,a.m_novel,a.m_game,a.m_baidu, a.m_tianya,a.m_le{}
</style>