config/routes.rb
LehaziCom::Application.routes.draw do

  resources :ads

  resources :friend_links

if Rails.env.development?
  match "/images/uploads/*path" => "gridfs#serve"
end
  get "index/friend_links" => "friend_links#index" ,:as => "friend_links"

  get "blogs"  => "blog#index", :as => "blogs"

  root :to => "home#index"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "we" =>  "we#index", :as => "we"
  get "tieba" =>  "we#tieba", :as => "tieba"
  get "tianya" =>  "we#tianya", :as => "tianya"
  get "douban" =>  "we#douban", :as => "douban"

  resources :tags

  resources :users  do
    resources :entries do
      resources :comments
    end

    resources :roles
      member do
        put "enable"
    end

  end
  resources :games do
    collection do
      get 'admin'
    end
  end
  resources :articles  do
    collection do
      get 'admin'
      get 'tag/:tag_id' ,:action => "index"
    end
  end
  resources :funs do
    collection do
      get 'admin'
      get 'tag/:tag_id' ,:action => "index"
    end
   end
  resources :novels  do
    collection do
      get 'admin'
    end
  end
  resources :categories  do
    collection do
      get 'admin'
    end
    resources :articles#, :name_prefix => 'category_' ,:path_prefix => '/categories/:category_id'
    resources :funs
    resources :games
  end

  resource :topics do
    collection do
      get 'tag/:tag_id' ,:action => "index"
    end
  end
  resources :forums do
    resources :topics do
      collection do
        get "newtopic"
        get "last"
      end
       resources :posts
    end
  end

  resources :sessions
  resources :infos

end

app/models/topic.rb
#encoding: UTF-8
require 'nokogiri'
require 'open-uri'
require 'ruby-debug'

class Topic < ActiveRecord::Base
  belongs_to :forum, :counter_cache => true
  belongs_to :user
  has_many :posts, :dependent => :delete_all
  has_many :taggings, :as => 'taggable'

  validates_presence_of :name
  validates_length_of :name, :maximum => 255

  #common
    def init_url_type(u , t)
      @url = u
      @type = t
    end

    def get_new_topic
      @temp
      @temp_posts ={}
      get_base_info
      @temp
    end

    def get_all_posts
      @temp_posts
    end


    def get_base_info
      if @type == 1
        chk_tieba_url != "0" ? do_get_tieba_topic : ""
      else if @type == 2
              chk_tianya_url != "0" ? do_get_tianya_topic : ""
          else if @type == 3
                  chk_douban_url != "0" ? do_get_douban_topic : ""
                end
        end
      end

    end
 #common- end


  #www.douban.com
  def do_get_douban_topic
    doc = Nokogiri::HTML(open(@url))
    init_get

    @title = doc.at_css("title").text

      doc.css(".pl20").each do |item|
        @lz = item.at_css("a").text
      end
      doc.css(".pl2").each do |item|
        @category = item.at_css("a").text.from(1)
      end
      doc.css(".topic-doc").each do |item|
        @created_at = item.at_css(".color-green").text
        item.css("p").each do |p|
          @first_post = @first_post << p.inner_html
        end

      end

      @temp={:title => @title, :username => @lz, :created_at => @created_at,
             :category => @category,:last_from_url => @url,
             :f_updated_at => @f_updated_at,
             :f_lz_updated_at => @f_lz_updated_at}
      #Get Posts
      @temp_posts[0] =[@lz,0,@created_at,@first_post]
      filter_douban_post doc
  end

  def filter_douban_post doc
    doc.css(".reply-doc").each do |item|
			@level_num += 1
			author = item.at_css("a").text
      created_time  = item.at_css("h4").text
			content= item.at_css("p").inner_html
      if author == @lz
        @reply_num += 1
        @temp_posts[@reply_num] = [author,@level_num,created_time, content]
        @temp[:f_lz_updated_at] =  created_time
      end

      @temp[:f_updated_at] =  created_time
    end

    doc.css(".next a").each do |link|
      if link.attr("href")
         href = link.attr("href")
         @temp[:last_from_url] =  href
         doc = Nokogiri::HTML(open(href))
         filter_douban_post doc

      end
    end
  end

	def chk_douban_url
		result = ""
		regEx = /douban\.com\/group\/topic\/[0-9]*/
		if regEx =~ @url
			result = ("http://www." << regEx.match(@url).to_s << "/")
		else
			return "0"
		end
		@url = result

    if Topic.find_all_by_from_url(@url).count > 0
      return "0"
    end

    @url
  end
 #www.douban.com  -end

 #baidu -tieba
  def do_get_tieba_topic
    doc = Nokogiri::HTML(open(@url))
    init_get
    @title = doc.at_css("h1").text
    @category = doc.at_css("cb").text
    #@lz = doc.at_css(".p_author_name").text

      post_json_str= doc.at_css(".l_post .p_post").attr("data-field")
			json_post = JSON.parse(post_json_str)
    @created_at = json_post["content"]["date"]
    @lz = json_post["author"]["name"]
    @temp={:title => @title, :username => @lz, :created_at => @created_at,
           :category => @category,:last_from_url => @url,
           :f_updated_at => @f_updated_at,
           :f_lz_updated_at => @f_lz_updated_at}

    filter_tieba_post doc
  end

  def filter_tieba_post doc
    doc.css(".p_postlist .l_post").each do |item|
      post_json_str = item.css(".p_post").attr("data-field")
      json_post = JSON.parse(post_json_str)

      created_at = json_post["content"]["date"]
      author = json_post["author"]["name"]
      level = json_post["content"]["floor"]
      content = gbk_changto_utf8 item.css(".d_post_content").inner_html #.force_encoding("GBK")
      #content = item.css(".d_post_content").inner_html.encode(Encoding.find("UTF-8"),Encoding.find("GBK"))

      if author == @lz
        @temp_posts[@reply_num] = [author,level,created_at, content]
        @temp[:f_lz_updated_at] =  created_at
        @reply_num += 1
      end

      @temp[:f_updated_at] =  created_at
    end

      doc.css(".p_thread .l_thread_info .l_posts_num .l_pager a").each do |link|
        if link.text == "下一页"
          href = "http://tieba.baidu.com" << link.attr("href")
          puts "next page is #{href}"
          @temp[:last_from_url] =  href
          doc = Nokogiri::HTML(open(href))
          filter_tieba_post doc
          break
        end
		  end
  end

  def chk_tieba_url
		result = ""
		regEx = /baidu\.com\/p\/[0-9]*/
		if regEx =~ @url
			result = ("http://tieba." << regEx.match(@url).to_s)
		else
			return "0"
		end
		@url = result

    if Topic.find_all_by_from_url(@url).count > 0
      return "0"
    end

    @url
  end
  #baidu-tieba -end


  #tianya--begin
  def do_get_tianya_topic
 doc = Nokogiri::HTML(open(@url))
    init_get
    @title = doc.at_css("h1 span a").parent.text
    @category = doc.at_css("h1 span a").text
    @lz = doc.at_css(".pagewrap table td a").text

		@created_at = doc.at_css(".pagewrap table td").text.last(19)
		@created_at = chk_datetime @created_at


		@tip = 0 #for get author and time
    @auth_time = {}
    @temp={:title => @title, :username => @lz, :created_at => @created_at,
           :category => @category,:last_from_url => @url,
           :f_updated_at => @f_updated_at,
           :f_lz_updated_at => @f_lz_updated_at}


    filter_tianya_post doc
  end
  def filter_tianya_post doc
    #单独获取 用户和时间 信息数组
    @first_do1 = true
    @first_do2 = true
        lz = doc.at_css(".pagewrap table td a").text
        created_at = doc.at_css(".pagewrap table td").text.last(19)
        created_at = chk_datetime created_at
        @auth_time[@tip] = [lz, created_at]
        @tip += 1

		doc.css(".allpost table").each do |item|
			author = item.at_css("center a").text
			time = chk_datetime item.at_css("center").text
			@auth_time[@tip] = [author, time]
      @tip += 1
		end

    doc.css(".allpost .post").each do |item|
      @level_num += 1
      if @first_do2 == true
        content = gbk_changto_utf8 item.inner_html #.encode(Encoding.find("UTF-8"),Encoding.find("GBK"))
        author = @auth_time[@level_num-1][0]
        created_at = @auth_time[@level_num-1][1]
        @temp_posts[@reply_num] = [author,@level_num,created_at, content]
        @reply_num += 1
        @first_do2 = false
        next
      end
      author = @auth_time[@level_num-1][0]
      created_at = @auth_time[@level_num-1][1]
      content= gbk_changto_utf8 item.inner_html #.encode(Encoding.find("UTF-8"),Encoding.find("GBK"))

      if author == @lz
        @temp_posts[@reply_num] = [author,@level_num,created_at, content]
        @temp[:f_lz_updated_at] =  created_at
        @reply_num += 1
      end

      @temp[:f_updated_at] =  created_at
    end

    doc.css("#pageDivTop a").each do |link|
			if link.text == "下一页"
				href =  link.attr("href")
				puts "next page is #{href}"
        @temp[:last_from_url] =  href
				doc = Nokogiri::HTML(open(href))
				filter_tianya_post doc
				break
			end
		end


  end


  def chk_tianya_url
   		result = ""
		regEx = /tianya\.cn\/\w*\/\w*\/([0-9]+|[a-z]*)\/[0-9]+\/[0-9]+\.shtml/
		if regEx =~ @url
			result = "http://www." << regEx.match(@url).to_s
		else
			return "0"
		end
		@url = result

    if Topic.find_all_by_from_url(@url).count > 0
      return "0"
    end

    @url
  end


  def init_get
    @title =""
		@lz = ""
    @created_at = ""
    @category = ""
    @first_post =""
    @f_updated_at = DateTime.now
    @f_lz_updated_at  = DateTime.now
    @reply_num=0
    @level_num=0
  end
  
  def chk_datetime str
	regEx = /2\d+-[0-9]+-[0-9]+\D[0-9]+:\d+:\d+/
	if regEx =~ str
		return regEx.match(str).to_s
	end
	return "0000"
  end

  def gbk_changto_utf8 str
	str
	#str.force_encoding('GBK')
	#str.encode('UTF-8', :invalid => :replace, :undef => :replace, :replace => '?').force_encoding('UTF-8')
	#str.encode('UTF-8')
    #str.encode(Encoding.find("UTF-8"),Encoding.find("GBK"))
  end
end

app/controllers/topics_controller.rb
#encoding: utf-8
class TopicsController < ApplicationController
  layout "we"

  before_filter :check_moderator_role, :only => [:destroy, :edit, :update]
  before_filter :login_required, :except => [:index, :show, :last, :newtopic ]

  # GET /topics
  # GET /topics.json
  def index

    @title = "乐贴"
    @keywords = "只看楼主,乐一下,了一下,leyixia,乐哈网,乐哈子,热贴,热吧,热区,豆瓣直播,贴吧,天涯,直播,脱水"
    @description = "热贴,热吧,百度贴吧,豆瓣直播,天涯论坛,"

    if params[:tag_id]
      @tag_name = Tag.find(params[:tag_id]).name
      @title <<"_" <<  @tag_name
      @keywords = @tag_name
      @topics = Topic.where( "taggings.tag_id = #{params[:tag_id].to_i} and taggings.taggable_type = 'topic'").joins(" right join taggings on topics.id = taggable_id").paginate(:page => params[:page], :per_page => 10,
                                              :include => :user,  :readonly => false).order ( 'topics.updated_at DESC')
    else
      @forum = Forum.find(params[:forum_id])
      @topics = Topic.where("forum_id=#{params[:forum_id].to_i} ").paginate(:page => params[:page],
                                                    :include => :user).order ( 'topics.updated_at DESC')
      @title = @forum.name
    end




    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics }
    end
  end

  def show
    #redirect_to forum_topic_posts_path(params[:forum_id],params[:id])
    redirect_to forum_topic_posts_path(@topic.forum, @topic)
  end

  def new
    @topic = Topic.new
    @post = Post.new
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    #获取-提交的信息
    @topic = Topic.new(:name => 'temp',:from_url => params[:topic][:from_url],
                        :forum_id => params[:forum_id].to_i, :user_id => current_user.id)

    #获取 主题、楼主、创建时间、
    @topic.init_url_type(@topic.from_url, @topic.forum_id)

    @ttt = @topic.get_new_topic

    if @ttt.nil?
      redirect_to new_forum_topic_path(@topic.forum), :notice => "错误，无法采集，可能该贴已存在！"
      return
    end


    @topic.update_attributes(:name => @ttt[:title], :created_at => @ttt[:created_at], :f_username => @ttt[:username],
                             :f_category => @ttt[:category], :last_from_url => @ttt[:last_from_url],
                             :f_updated_at => @ttt[:f_updated_at], :f_lz_updated_at => @ttt[:f_lz_updated_at])

    @topic.save!

    @topic.get_all_posts.each do |key,value|
      @post = Post.new(:body => value[3],:created_at => value[2],:f_level_num => value[1], :topic_id => @topic.id, :user_id => current_user.id)
      @post.save!
    end



    respond_to do |format|
        format.html { redirect_to forum_topic_posts_path(@topic.forum,@topic), notice: 'Topic was successfully created.' }
        #format.json { render json: @topic, status: :created, location: @topic }
    end


  rescue ActiveRecord::RecordInvalid
    respond_to do |format|
      format.html { render action: "new" }
      format.json { render json: @topic.errors, status: :unprocessable_entity }
    end

  end

  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to forum_topics_path, notice: 'Topic was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.posts.each {|post| post.destroy }
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to forum_topics_path }
      format.json { head :ok }
    end
  end

  def newtopic
    @forum = Forum.find(params[:forum_id])
    @topics = Topic.where("forum_id=#{params[:forum_id].to_i} ").paginate(:page => params[:page],
                                                    :include => :user).order ( 'topics.f_updated_at DESC')

  end
  def last
  @forum = Forum.find(params[:forum_id])
  @topics = Topic.where("forum_id=#{params[:forum_id].to_i} ").paginate(:page => params[:page],
                                                  :include => :user).order ( 'topics.posts_count DESC')

  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for @topic ,:url => forum_topic_path do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :forum_id %><br />
    <%= f.number_field :forum_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br />
    <%= f.datetime_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :updated_at %><br />
    <%= f.datetime_select :updated_at %>
  </div>
  <div class="field">
    <%= f.label :posts_count %><br />
    <%= f.number_field :posts_count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/_list.html.erb
<div class="span-23">
  <hgroup>
    <label>当前位置： </label>
    <%=	 link_to '乐贴', forums_path %>  »
    <%= @forum.blank? ? @tag_name : @forum.name %>
  <span class="right">
      <label>热门搜索：</label>
  </span>
  </hgroup>
  <% unless @forum.blank? %>
  <hgroup style="margin: 5px; padding: 5px 0px 0 20px; border-top: 1px solid #dddddd; border-bottom: 1px solid #dddddd; " >
    <span class="border hot"><%= link_to '最近查看', forum_topics_path(@forum) %> </span>
    <span class="border last"><%= link_to '热度排序', last_forum_topics_path(@forum) %> </span>
    <span class="newtopic"><%= link_to '最新更新', newtopic_forum_topics_path(@forum) %> </span>
  </hgroup>
  <% end %>
</div>
<div class="span-23">
<hgroup>
<%= will_paginate @topics ,:class => 'digg_pagination' %>
</hgroup>
<table>
  <tbody>
  <!--thead>
    <%	 if is_logged_in? %>
        <%=	 link_to '发帖', new_forum_topic_path %>
      <%	 else %>
  <%= link_to '登陆', login_url	  %>
    <%	 end %>
  </thead-->
  <tr>
    <th>分类</th>
    <th>主题</th>
    <!--th>下载</th-->
    <th>点击/帖数</th>
    <th>作者</th>
  </tr>

<% @topics.each do |topic| %>
  <tr>
    <td><%=	 topic.f_category %> </td>
    <td>
      <%= link_to topic.name, forum_topic_posts_path(topic.forum,topic) %>
      <%	 if is_logged_in? and current_user.has_roles?('Moderator') %>
        <br/>
          <small>
            <%= link_to '编辑', edit_forum_topic_path(topic.forum,topic)%>
            <%=	 link_to '删除',forum_topic_path(topic.forum,topic), method: :delete ,:confirm => '确定？'  %>
          </small>
      <%	 end %>
    </td>
    <!--td> <%= link_to '下载/TxT/HTML' , '#'%> </td-->
    <td> <%= topic.click_times %>/<%= topic.posts_count %> </td>
    <td><%= topic.f_username %><br>

    <span class="small"><%= topic.updated_at.strftime "%Y-%m-%d %H:%M:%S" %></span></td>
  </tr>
<% end %>
  </tbody>
</table>
<hgroup>
 <%= will_paginate @topics ,:class => 'digg_pagination' %>
 </hgroup>
</div>

app/views/topics/edit.html.erb
<h2>编辑主题</h2>

<%=	 @topic.name %>
<%= form_for(@topic ,:url => forum_topic_path(@topic.forum_id, @topic.id)) do |f| %>
         <p>标题：<br /> <%=	 f.text_field :name, :size => 40 %> </p>

         <%= submit_tag '保存' %>
         <%= link_to '取消', forum_topics_path %>
<%	 end %>

app/views/topics/index.html.erb
<%= render "topics/list" %>
<style>
 .hot a{color:#000000; background: #fff; font-weight: bold;}
</style>

app/views/topics/last.html.erb
<%= render "topics/list" %>

<style>
 .last a{color:#000000; background: #fff; font-weight: bold;}
</style>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= form_for(@topic ,:url => forum_topics_path) do |f| %>
         <p>标题：<br /> <%=	 f.text_field :name, :size => 40 %> </p>
         <p>采集网址：<br /> <%=	 f.text_field :from_url, :size => 80 %> </p>

         <p>内容：<br/> <%=	text_field :post, :body, :size => 20 %></p>
         <%= submit_tag '保存' %>
<%	 end %>

<%= link_to 'Back', forum_topics_path %>

app/views/topics/newtopic.html.erb
<%= render "topics/list" %>
<style>
 .newtopic a{color:#000000; background: #fff; font-weight: bold;}
</style>