config/routes.rb
LehaziCom::Application.routes.draw do

  resources :ads

  resources :friend_links

if Rails.env.development?
  match "/images/uploads/*path" => "gridfs#serve"
end
  get "index/friend_links" => "friend_links#index" ,:as => "friend_links"

  get "blogs"  => "blog#index", :as => "blogs"

  root :to => "home#index"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "we" =>  "we#index", :as => "we"
  get "tieba" =>  "we#tieba", :as => "tieba"
  get "tianya" =>  "we#tianya", :as => "tianya"
  get "douban" =>  "we#douban", :as => "douban"

  resources :tags

  resources :users  do
    resources :entries do
      resources :comments
    end

    resources :roles
      member do
        put "enable"
    end

  end
  resources :games do
    collection do
      get 'admin'
    end
  end
  resources :articles  do
    collection do
      get 'admin'
      get 'tag/:tag_id' ,:action => "index"
    end
  end
  resources :funs do
    collection do
      get 'admin'
      get 'tag/:tag_id' ,:action => "index"
    end
   end
  resources :novels  do
    collection do
      get 'admin'
    end
  end
  resources :categories  do
    collection do
      get 'admin'
    end
    resources :articles#, :name_prefix => 'category_' ,:path_prefix => '/categories/:category_id'
    resources :funs
    resources :games
  end

  resource :topics do
    collection do
      get 'tag/:tag_id' ,:action => "index"
    end
  end
  resources :forums do
    resources :topics do
      collection do
        get "newtopic"
        get "last"
      end
       resources :posts
    end
  end

  resources :sessions
  resources :infos

end

app/controllers/home_controller.rb
# encoding: utf-8
class HomeController < ApplicationController
  def get_random_numbers  count
   rd = (1..count).to_a.sample(9)
  end

  def index

    #获取前 18条娱乐相关新闻信息 含有分类名称
    #获取前 27条娱乐相关新闻信息 含有分类名称
    #@articles = Article.where(:published => true).paginate(:page => params[:page],
    #                                                :include => :user).order('published_at DESC')
    @top_articles = Article.where(:published => true).find(:all, :order => 'published_at DESC',:include => :category, :limit => 9 )
    @top_topics = Topic.find(:all, :order => 'updated_at DESC', :limit => 9 )

    #精选集
    @top_funs = Fun.find(:all, :order => 'created_at DESC', :limit => 18 )
=begin
    #时事笑话
    @top_funs_news = Fun.where(:category_id => 5).find(:all, :order => 'created_at DESC', :limit => 18 )
    #学生时代
    @top_funs_student = Fun.where(:category_id => 8).find(:all, :order => 'created_at DESC', :limit => 18 )
    #IT故事
    @top_funs_it = Fun.where(:category_id => 12).find(:all, :order => 'created_at DESC', :limit => 18 )
    #搞笑网文
    @top_funs_net = Fun.where(:category_id => 6).find(:all, :order => 'created_at DESC', :limit => 18 )
    #冷笑话
    @top_funs_cold = Fun.where(:category_id => 4).find(:all, :order => 'created_at DESC', :limit => 18 )
    #老外幽默
    @top_funs_for = Fun.where(:category_id => 11).find(:all, :order => 'created_at DESC', :limit => 18 )
    #情感趣事
    @top_funs_love = Fun.where(:category_id => 9).find(:all, :order => 'created_at DESC', :limit => 18 )
=end


    @count = Fun.count
    #随机抽取
    @random_funs =Fun.find(get_random_numbers(@count))

    @title = "首页"
    #@keywords = tag_get("home", 1, 20)
    @keywords = "乐一下,了一下,leyixia,乐哈网,乐哈子,娱乐广场,娱乐,旅游,lehazi,小笑话,幽默,漂流客,租房客"
    @description = "乐哈网，笑话，热贴热吧，娱乐信息"
    #Fun.find(:all, :order => 'click_time DESC', :limit => 9 )

    #10.times.map{ 20+Random.rand(11) }
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="span-13 list round">
  <hgroup>
    <span class="right"><%= link_to t('enter'),forums_path, :target => '_blank'%></span>
    <h4>最新帖子</h4>
</hgroup>
<ul>
<% @top_topics.each do |topic| %>
<li>
    <%= link_to topic.name.truncate(36), forum_topic_posts_path(topic.forum,topic.id) , :target => "_blank"%>
</li>
<% end %>
</ul>
</div>

<div class="span-8 list round">
  <hgroup>
    <span class="right"><%= link_to '更多' ,articles_path,:target => '_blank'%></span>
    <h4>娱乐信息</h4>
  </hgroup>
<ul>
<% @top_articles.each do |article| %>
<li>
    <% if article.category  %>
    <%= link_to ('['+article.category.name+'] '+article.title).truncate(25), article ,:title => article.title,  :target => '_blank'%>
    <% else %>
    <%= link_to article.title.truncate(24), article, :title => article.title, :target => '_blank' %>
    <% end %>
</li>
<% end %>
</ul>
</div>
<div class="fixed clearfix"></div>


<div class="span-22 prepend-top list_fun round">
<hgroup>
  <span class="right"><%= link_to '更多'  ,category_funs_path(5),:target => '_blank'%></span>
  <h4>最新笑话</h4>
</hgroup>
    <ul>
        <% @top_funs.each do |fun| %>
        <li><span class="dian01">·</span>
            <%= link_to fun.title, fun ,:target => '_blank'%>
        </li>
        <% end %>
    </ul>

</div>
<div class="fixed clearfix"></div>