config/routes.rb
LehaziCom::Application.routes.draw do

  resources :ads

  resources :friend_links

if Rails.env.development?
  match "/images/uploads/*path" => "gridfs#serve"
end
  get "index/friend_links" => "friend_links#index" ,:as => "friend_links"

  get "blogs"  => "blog#index", :as => "blogs"

  root :to => "home#index"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "we" =>  "we#index", :as => "we"
  get "tieba" =>  "we#tieba", :as => "tieba"
  get "tianya" =>  "we#tianya", :as => "tianya"
  get "douban" =>  "we#douban", :as => "douban"

  resources :tags

  resources :users  do
    resources :entries do
      resources :comments
    end

    resources :roles
      member do
        put "enable"
    end

  end
  resources :games do
    collection do
      get 'admin'
    end
  end
  resources :articles  do
    collection do
      get 'admin'
      get 'tag/:tag_id' ,:action => "index"
    end
  end
  resources :funs do
    collection do
      get 'admin'
      get 'tag/:tag_id' ,:action => "index"
    end
   end
  resources :novels  do
    collection do
      get 'admin'
    end
  end
  resources :categories  do
    collection do
      get 'admin'
    end
    resources :articles#, :name_prefix => 'category_' ,:path_prefix => '/categories/:category_id'
    resources :funs
    resources :games
  end

  resource :topics do
    collection do
      get 'tag/:tag_id' ,:action => "index"
    end
  end
  resources :forums do
    resources :topics do
      collection do
        get "newtopic"
        get "last"
      end
       resources :posts
    end
  end

  resources :sessions
  resources :infos

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles, :dependent => :nullify  #you can dependent => :destroy to del all article
  has_many :infos, :dependent => :nullify
  has_many :funs, :dependent => :nullify
  has_many :novels, :dependent => :nullify
  has_many :games, :dependent => :nullify


  validates_length_of :name, :maximum => 80
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  layout "we"
before_filter :check_administrator_role,:except => :show
  # GET /categories
  # GET /categories.json
  def index


    @categories = Category.all
    @htmlmenu = infoaddresstree


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end

  end


  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :ok }
    end
  end

  def admin
    @categories = Category.find(:all)
    respond_to do |format|
      format.html
      format.json { render json: @categories }
      format.xml { render xml: @categories }
    end
  end



def infoaddresstree
    @htmlmenu=""
    @htmlmenu+= "<ul>"
    @root = Category.find(:all,:conditions=>['parent_id=1'])
    @root.each { |item|
      if Category.find_by_parent_id(item.id)
      @htmlmenu+= "<li><a href='#ChildMenu#{item.id}' onclick=\"DoMenu('ChildMenu#{item.id}')\">"
      else
        @htmlmenu+= "<li><a href='/categories/#{item.id}'>"
      end
      @htmlmenu+= item.name
      @htmlmenu+= "</a>"
      buildmenu item
      @htmlmenu+= "</li>"
    }
    @htmlmenu+= "</ul>"
    @htmlmenu
end

private
  def buildmenu category
    @children = Category.find_all_by_parent_id(category.id)
    if @children.size!=0
      @htmlmenu+= "<ul id='ChildMenu#{category.id}' class='collapsed'>"
      @children.each { |item|
        if Category.find_all_by_parent_id(item.id).size!=0
          @htmlmenu+= "<li><a href='#ChildMenu#{item.id}' onclick=\"DoMenu('ChildMenu#{item.id}')\">"
        else
                @htmlmenu+= "<li><a href='/categories/#{item.id}'>"
        end

        @htmlmenu+= item.name
        @htmlmenu+= "</a>"
        buildmenu item
        @htmlmenu+= "</li>"
        }
      @htmlmenu+= "</ul>"

    end
end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br />
    <%= f.number_field :parent_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/admin.html.erb
<h1>Listing categories</h1>
<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Parent</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.id %></td>
    <td><%= category.name %></td>
    <td><%= category.parent_id %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', admin_categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>
<%=	 raw(@htmlmenu) %>
<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Parent</th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.id %></td>
    <td><%= category.name %></td>
    <td><%= category.parent_id %></td>
    <td><%= link_to 'Show', category %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_categories_path %>

app/views/categories/show.html.erb
<p>
  <b>Id:</b>
  <%= @category.id %>
</p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Parent:</b>
  <%= @category.parent_id %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>